### PR TITLE
use serverV2 in server details to speed up page load

### PR DESCRIPTION
**Pull request by Palabola**
## Summary by CodeRabbit

- **New Features**
  - Added new methods for querying server prices and benchmarks, enhancing data retrieval capabilities.
  - Introduced multiple API calls in the Server Details component for comprehensive server data fetching.
  - Added a new region option for server pricing, expanding geographical options.

- **Bug Fixes**
  - Corrected typographical errors in documentation comments across multiple files for improved clarity.

- **Documentation**
  - Enhanced documentation comments to clarify expected inputs and outputs in several interfaces and methods.

- **Refactor**
  - Updated method signatures and parameter handling for improved usability and maintainability in the API service.

### CODE REVIEW

**Comment by daroczig** [comment]
TODO missing $core

**Comment by daroczig** [comment]
Somehow some of the l1/l2/l3 cache amounts got added to the memory bandwidth chart:

image

See https://deploy-preview-98--creative-choux-a3c817.netlify.app/compare?instances=W3sidmVuZG9yIjoiYXdzIiwic2VydmVyIjoiYzZnZC5tZWRpdW0ifSx7InZlbmRvciI6ImdjcCIsInNlcnZlciI6Im4xLXN0YW5kYXJkLTEifSx7InZlbmRvciI6ImdjcCIsInNlcnZlciI6ImcxLXNtYWxsIn1d vs https://sparecores.com/compare?instances=W3sidmVuZG9yIjoiYXdzIiwic2VydmVyIjoiYzZnZC5tZWRpdW0ifSx7InZlbmRvciI6ImdjcCIsInNlcnZlciI6Im4xLXN0YW5kYXJkLTEifSx7InZlbmRvciI6ImdjcCIsInNlcnZlciI6ImcxLXNtYWxsIn1d

**Comment by Palabola** [comment]
> Somehow some of the l1/l2/l3 cache amounts got added to the memory bandwidth chart:
> 
> image
> 
> See https://deploy-preview-98--creative-choux-a3c817.netlify.app/compare?instances=W3sidmVuZG9yIjoiYXdzIiwic2VydmVyIjoiYzZnZC5tZWRpdW0ifSx7InZlbmRvciI6ImdjcCIsInNlcnZlciI6Im4xLXN0YW5kYXJkLTEifSx7InZlbmRvciI6ImdjcCIsInNlcnZlciI6ImcxLXNtYWxsIn1d vs https://sparecores.com/compare?instances=W3sidmVuZG9yIjoiYXdzIiwic2VydmVyIjoiYzZnZC5tZWRpdW0ifSx7InZlbmRvciI6ImdjcCIsInNlcnZlciI6Im4xLXN0YW5kYXJkLTEifSx7InZlbmRvciI6ImdjcCIsInNlcnZlciI6ImcxLXNtYWxsIn1d

BWMem Annotation lines did not reset. Fixed in [https://github.com/SpareCores/sc-www/pull/106](url)

**Comment by daroczig** [comment]
why not in this PR? :thinking:

**Pull request merged**
